CC=g++
IFLAGS=-Iinclude -g
CFLAGS=-c
RM=rm


array:
	$(CC) src/array.cpp -o bin/array $(IFLAGS)

n2:
	$(CC) src/N2.cpp -o bin/n2 $(IFLAGS)

pix:
	$(CC) src/Pixel.cpp -o bin/pixel $(IFLAGS)

image:
	$(CC) src/image.cpp -o bin/img $(IFLAGS)

tri:
	$(CC) src/triangle.cpp -o bin/tri $(IFLAGS)

mesh:
	$(CC) src/Mesh.cpp -o bin/mesh $(IFLAGS)

clean:
	$(RM) bin/*
